USE PD_311_DDL;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Directions')
BEGIN
CREATE TABLE Teachers
(
	teacher_id		INT PRIMARY KEY IDENTITY(1,1),
	last_name		NVARCHAR(150)	NOT NULL,
	first_name		NVARCHAR(150)	NOT NULL,
	middle_name		NVARCHAR(150),
	birth_date		DATE			NOT NULL,
	works_sice		DATE			NOT NULL,
	rate			MONEY			NOT NULL
);
END
GO
